fixing daily_tvl table
FlipsideCrypto/sql_models pull request #193
Opened 2021-12-01 21:47 UTC by flipside-kellen

2021-12-01 21:48 UTC, flipside-kellen commented
Previously we were double cumulative summing that column

2021-12-01 22:03 UTC, juls858 requested changes

2021-12-01 22:03 UTC, juls858 commented on models/thorchain/thorchain__total_value_locked.sql
> +  GROUP BY 1,2
please use actual column names here.. we are trying to elinate the user of ordinal references for al new code.

2021-12-02 00:14 UTC, juls858 approved these changes

2021-12-02 00:14 UTC, merged