An 524/account for internal txns nick
FlipsideCrypto/sql_models pull request #233
Opened 2022-01-04 22:42 UTC by nickpayiatis

-Added column inner_tx to specify whether transactions were inner transactions or not
-broke out inner transactions into their own transactions to account for the changes in the 2.8 indexer.
-resolved appl transactions where asset_id was being set as app_id when this type of transaction does not have a asset.

2022-01-05 18:56 UTC, juls858 requested changes
this is not built on 2_8_0.. please refactor and use the new bronze schema.

2022-01-06 07:33 UTC, nickpayiatis commented on models/algorand/silver/silver_algorand__transactions.sql
> +  genisis_hash IS NOT NULL
Conversation for future reference: https://flipsidecrypto.slack.com/archives/C015ULZ1Y7L/p1641413381331900

2022-01-06 07:36 UTC, nickpayiatis commented on models/algorand/silver/silver_algorand__transactions.sql
> +  genisis_hash IS NOT NULL
All transaction tables have been modified so we are no longer breaking out inner transactions from their parent transactions. Instead we are using the txn's with no txid(these are actually the inner transactions) and we are tying in the TXID from their parent transactions with the inner_txids model. The inner_txids model should be scheduled before the other silver models.

2022-01-07 17:52 UTC, juls858 requested changes
incremental loads are failing...
```
Completed with 7 errors and 0 warnings:

Database Error in model silver_algorand__application_call_transaction (models/algorand/silver/silver_algorand__application_call_transaction.sql)
  002028 (42601): SQL compilation error:
  ambiguous column name '_FIVETRAN_SYNCED'

Database Error in model silver_algorand__asset_transfer_transaction (models/algorand/silver/silver_algorand__asset_transfer_transaction.sql)
  002028 (42601): SQL compilation error:
  ambiguous column name '_FIVETRAN_SYNCED'

Database Error in model silver_algorand__transactions (models/algorand/silver/silver_algorand__transactions.sql)
  002028 (42601): SQL compilation error:
  ambiguous column name '_FIVETRAN_SYNCED'

Database Error in model silver_algorand__asset_freeze_transaction (models/algorand/silver/silver_algorand__asset_freeze_transaction.sql)
  002028 (42601): SQL compilation error:
  ambiguous column name '_FIVETRAN_SYNCED'

Database Error in model silver_algorand__payment_transaction (models/algorand/silver/silver_algorand__payment_transaction.sql)
  002028 (42601): SQL compilation error:
  ambiguous column name '_FIVETRAN_SYNCED'

Database Error in model silver_algorand__key_registration_transaction (models/algorand/silver/silver_algorand__key_registration_transaction.sql)
  002028 (42601): SQL compilation error:
  ambiguous column name '_FIVETRAN_SYNCED'

Database Error in model silver_algorand__asset_configuration_transaction (models/algorand/silver/silver_algorand__asset_configuration_transaction.sql)
  002028 (42601): SQL compilation error:
  ambiguous column name '_FIVETRAN_SYNCED'

Done. PASS=15 WARN=0 ERROR=7 SKIP=7 TOTAL=29```

2022-01-07 19:17 UTC, juls858 approved these changes

2022-01-07 20:09 UTC, merged