An 470/synthetic balances terra
FlipsideCrypto/sql_models pull request #240
Opened 2022-01-05 22:41 UTC by amasucci13

- Combined synthetic balances with native balances already in gold terra.daily_balances
- Moved de-dupeing logic to silver.synthetic_balances instead of gold. 
-  Added is_native (boolean) column
- Added tests for silver synthetic balances and terra.daily_balances (looking at last 30 days)
- All tests pass except for silver synthetic - recent data. Last date is 12/30 (Looking into root cause).
- Ran full refreshes and incremental refreshes successfully.

2022-01-17 20:13 UTC, jkallogjeri approved these changes

2022-01-19 19:11 UTC, juls858 requested changes

2022-01-19 19:11 UTC, juls858 commented on models/terra/silver/silver_terra__block_synthetic_balances.sql
> +WHERE 1 = 1
this line doesn't do anything

2022-01-19 19:11 UTC, juls858 commented on models/terra/silver/silver_terra__block_synthetic_balances.sql
> +AND system_created_at :: DATE >= ( SELECT DATEADD('day', -1, MAX(system_created_at :: DATE)) FROM {{ this }})
this should be pushed into the inner query for optimization. We should filter fist and then dedupe as it's more efficient to dedupe less rows than more rows.  Also, using the [qualify](https://github.com/FlipsideCrypto/sql_models/blob/a643e98f61e6cd427083cc584b2c4441b835f9e6/models/crosschain/silver/silver_crosschain__address_labels.sql#L33-L35) statement might save you a few lines of code

2022-01-19 19:11 UTC, juls858 commented on models/terra/silver/silver_terra__block_synthetic_balances.yml
> +              where: BLOCK_TIMESTAMP > CURRENT_DATE - 30
the individual column level test should be fast wtihout the date filter.. can you provide verify how long these individual tests take? If the time is reasonable, a couple of mintes, lets remove the date filter. 

The unique key test is probably the one that takes the longest, so we can keep the date filter there for now

2022-01-19 19:11 UTC, juls858 commented on models/terra/silver/silver_terra__block_synthetic_balances.sql
> +AND system_created_at :: DATE >= ( SELECT DATEADD('day', -1, MAX(system_created_at :: DATE)) FROM {{ this }})
lets change the incremental window to 2 days just to be safe.

2022-02-07 21:49 UTC, juls858 approved these changes

2022-02-07 21:49 UTC, merged