update the balance to repoint to the bronze model
FlipsideCrypto/sql_models pull request #266
Opened 2022-01-21 21:41 UTC by xiuy001

Related to this ticket: https://team-1612274056224.atlassian.net/browse/AN-500. The number of the table drops, not sure whether this is expected.

2022-02-25 16:50 UTC, juls858 requested changes
can we change to incremetnal strategy to merge?
and fix the unique key?
```
  unique_key = 'date',
  incremental_strategy = 'delete+insert',
```

2022-02-25 16:50 UTC, juls858 commented on models/terra/dbt/terra_dbt__balances.sql
> +  WHERE date(block_timestamp) < '2020-10-04' AND block_number <= 3820000
why do we need the extra date filter?

2022-02-25 16:50 UTC, juls858 commented on models/terra/dbt/terra_dbt__balances.sql
> +    record_content :model :name :: STRING IN (
pleasee use classname instead.. these configs will change as we change node providers. The class names will not.

2022-02-25 16:50 UTC, juls858 commented on models/terra/dbt/terra_dbt__balances.sql
> +    *
please convert to column names

2022-02-25 16:52 UTC, juls858 requested changes
see comments

2022-02-25 16:52 UTC, juls858 commented on models/terra/dbt/terra_dbt__balances.sql
> +AND (
incremental logic should use _inserted_timestamp

2022-02-25 19:02 UTC, xiuy001 commented on models/terra/dbt/terra_dbt__balances.sql
> +  WHERE date(block_timestamp) < '2020-10-04' AND block_number <= 3820000
Here is because the source('shared', 'terra_balances') includes all the blockchain data, Columbus-3, 4 and 5 and so put a filter here to only includes the data before block_number <= 3820000 which is Columbus-3

2022-02-25 22:50 UTC, juls858 requested changes
> Here is because the source('shared', 'terra_balances') includes all the blockchain data, Columbus-3, 4 and 5 and so put a filter here to only includes the data before block_number <= 3820000 which is Columbus-3 

this means we don't need the date only the block number?

2022-02-25 23:31 UTC, xiuy001 commented on models/terra/dbt/terra_dbt__balances.sql
> +  WHERE date(block_timestamp) < '2020-10-04' AND block_number <= 3820000
We need to include both date and block_number, because when the txs turns to columbus-4, the block_number dropped from 3820000 to 0 and started over, only use block_number will include the columbus-4 data also. And in the blockchain column, both Columbus-3 and 4 labeled as terra, so there is no way to distinguish them out.

2022-02-26 00:15 UTC, juls858 approved these changes

2022-02-28 12:45 UTC, merged