Refactored Solana Votes to present count of votes per block id
FlipsideCrypto/sql_models pull request #279
Opened 2022-01-31 20:26 UTC by jhuhnke

This PR does two things: it aggregates the gold Solana votes table to provide number of votes per block and 2. removes an unnecessary where clause from silver_solana.votes. 

Will require a full refresh of solana.votes as columns with data that is unique per individual vote have been removed.

2022-01-31 22:49 UTC, nickpayiatis requested changes

2022-01-31 22:49 UTC, nickpayiatis commented on models/solana/gold/solana__votes.sql
> +GROUP BY block_id, block_timestamp, blockchain
Group bys should not be happening in gold models as they are time intensive. I'd suggest creating a silver model that references of your original silver vote model to aggregate vote count by block. Then create a gold view to reference that.

2022-01-31 22:49 UTC, nickpayiatis commented on models/solana/silver/silver_solana__votes.sql
> +  WHERE tx :transaction:message:instructions[0]:programId :: STRING = 'Vote111111111111111111111111111111111111111'
looks good

2022-02-01 18:40 UTC, nickpayiatis requested changes

2022-02-01 18:40 UTC, nickpayiatis commented on models/solana/gold/solana__votes.sql
>  ORDER BY block_id DESC
Order by is also a computationally expensive function that should be in silver instead of gold. It shouldn't be needed at all as users can choose to order on the frontend. If it is included, it should be in the silver model

2022-02-02 17:53 UTC, nickpayiatis requested changes
getting failed timestamp in the silver solana votes
 `(base) nickpayiatis@Nicks-MacBook-Pro sql_models % dbt test --models models/solana/silver/silver_solana__votes.sql   
Running with dbt=0.21.0
Found 317 models, 2688 tests, 0 snapshots, 1 analysis, 583 macros, 0 operations, 3 seed files, 109 sources, 0 exposures

12:50:04 | Concurrency: 4 threads (target='dev')
12:50:04 | 
12:50:04 | 1 of 6 START test dbt_expectations_expect_row_values_to_have_recent_data_silver_solana__votes_BLOCK_TIMESTAMP__day__1 [RUN]
12:50:04 | 2 of 6 START test dbt_utils_unique_combination_of_columns_silver_solana__votes_BLOCK_ID [RUN]
12:50:04 | 3 of 6 START test not_null_silver_solana__votes_BLOCKCHAIN........... [RUN]
12:50:04 | 4 of 6 START test not_null_silver_solana__votes_BLOCK_ID............. [RUN]
12:50:06 | 3 of 6 PASS not_null_silver_solana__votes_BLOCKCHAIN................. [PASS in 1.95s]
12:50:06 | 5 of 6 START test not_null_silver_solana__votes_BLOCK_TIMESTAMP...... [RUN]
12:50:06 | 4 of 6 PASS not_null_silver_solana__votes_BLOCK_ID................... [PASS in 1.97s]
12:50:06 | 6 of 6 START test not_null_silver_solana__votes_NUM_VOTES............ [RUN]
12:50:07 | 2 of 6 PASS dbt_utils_unique_combination_of_columns_silver_solana__votes_BLOCK_ID [PASS in 2.02s]
12:50:07 | 1 of 6 FAIL 1 dbt_expectations_expect_row_values_to_have_recent_data_silver_solana__votes_BLOCK_TIMESTAMP__day__1 [FAIL 1 in 2.39s]
12:50:07 | 6 of 6 PASS not_null_silver_solana__votes_NUM_VOTES.................. [PASS in 0.91s]
12:50:07 | 5 of 6 FAIL 95027 not_null_silver_solana__votes_BLOCK_TIMESTAMP...... [FAIL 95027 in 0.99s]
12:50:07 | 
12:50:07 | Finished running 6 tests in 16.12s.

Completed with 2 errors and 0 warnings:

Failure in test dbt_expectations_expect_row_values_to_have_recent_data_silver_solana__votes_BLOCK_TIMESTAMP__day__1 (models/solana/silver/silver_solana__votes.yml)
  Got 1 result, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/solana/silver/silver_solana__votes.yml/schema_test/dbt_expectations_expect_row_va_cb9e5a53b612cd722027ba49b00e8689.sql

Failure in test not_null_silver_solana__votes_BLOCK_TIMESTAMP (models/solana/silver/silver_solana__votes.yml)
  Got 95027 results, configured to fail if != 0
`

2022-02-02 23:59 UTC, desmond-hui requested changes

2022-02-02 23:59 UTC, desmond-hui commented on models/solana/gold/solana__votes_daily_agg.sql
> +{{ config(
This file name should change to use `block_agg` as well

2022-02-02 23:59 UTC, desmond-hui commented on models/solana/silver/silver_solana__votes_block_agg.sql
> +    ingested_at
There is no need to have ingest_at as a column or in the group by

2022-02-02 23:59 UTC, desmond-hui commented on models/solana/silver/silver_solana__votes_block_agg.sql
> +  GROUP BY block_id, blockchain, ingested_at
See above comment

2022-02-02 23:59 UTC, desmond-hui commented on models/solana/silver/silver_solana__votes_block_agg.sql
> +  t.block_timestamp DESC)) = 1
We shouldn't use qualify here unless we need to since it is an expensive operation.  It would be better to join on a subquery of bronze_solana.transactions than to join on the full thing and then using the qualify to remove records.

example: `LEFT OUTER JOIN (select distinct block_id, block_timestamp from flipside_dev_db.bronze_solana.transactions) t 
ON v.block_id = t.block_id`

I ran the full loads using a 2XL machine using the current query vs. the suggested and we get 100% faster performance with the latter.

2022-02-03 18:11 UTC, desmond-hui requested changes

2022-02-03 18:11 UTC, desmond-hui commented on models/solana/silver/silver_solana__votes_block_agg.sql
> +LEFT OUTER JOIN {{ ref('bronze_solana__transactions') }} t
We really should be joining on the distinct of block_id, block_timestamp in a subquery.  The reason to do that instead of doing the distinct after is because we want to reduce the number of rows created by the join.  There is no reason to join N times more rows than we want to.  

Took 28s to run this query on 2XL.  Changing to use the subquery (code below) reduces the run time to 4s

`LEFT OUTER JOIN (select distinct block_id, block_timestamp from  {{ ref('bronze_solana__transactions') }}) t on v.block_id = t.block_id`

2022-02-03 20:20 UTC, desmond-hui approved these changes

2022-02-04 16:16 UTC, nickpayiatis approved these changes

2022-02-04 18:09 UTC, nickpayiatis approved these changes

2022-02-04 18:09 UTC, merged