An 660/update reference to legacy tables
FlipsideCrypto/sql_models pull request #282
Opened 2022-02-01 22:36 UTC by desmond-hui

- Modify references to legacy silver tables to newer maintained tables
- Modify scope of references to legacy silver tables to ensure they only used for older data

2022-02-03 23:19 UTC, nickpayiatis requested changes

2022-02-03 23:19 UTC, nickpayiatis commented on models/crosschain/silver/silver_crosschain__address_labels.yml
> +              where: BLOCKCHAIN = 'algorand'
Algorand Addresses have different layout. Algorand addresses are a string 58 random capital letters and numbers

2022-02-03 23:27 UTC, desmond-hui commented on models/crosschain/silver/silver_crosschain__address_labels.yml
> +              where: BLOCKCHAIN = 'algorand'
Hmm, let me look at it.  This is actually someone else's change that I just re-factored because the old polygon and ethereum checks were checking for the same thing so I moved them into one

2022-02-03 23:29 UTC, desmond-hui commented on models/crosschain/silver/silver_crosschain__address_labels.yml
> +              where: BLOCKCHAIN = 'algorand'
@nickpayiatis - I think the current check works the way you described

` - dbt_expectations.expect_column_value_lengths_to_equal:
              value: 58
              where: BLOCKCHAIN = 'algorand'`

2022-02-08 22:00 UTC, nickpayiatis approved these changes

2022-02-08 22:00 UTC, merged