An 613 fix terra tests
FlipsideCrypto/sql_models pull request #284
Opened 2022-02-03 01:35 UTC by desmond-hui

- Add new bespoke test for null threshold.  This is used to replace strict not null tests to allow for a % of values to be null
- Apply null threshold tests to some terra columns that may have nulls due to missing values in base tables (like address_labels)
- Add conditions to columns checks where appropriate (ex: some column may only be populated for columbus-5 records)
- Modify data models so that they proper columns can be applied for unique key check and/or add business logic to select the appropriate records
- Remove use of REGEXP for removing `"`s from object values.  They should be casted to the appropriate data type instead (ex: `::string`)

NOTE: There are gap tests that will fail in silver_terra.blocks and silver_terra.tax_rate.  This is due to missing blocks in bronze and not in scope for this PR.

2022-02-03 20:04 UTC, juls858 requested changes
not sure which ones are supposed to fail, but there are a few bad tests
```
Completed with 40 errors and 0 warnings:

Failure in test dbt_expectations_expect_row_values_to_have_recent_data_terra__validator_voting_power_BLOCK_TIMESTAMP__day__1 (models/terra/gold/terra__validator_voting_power.yml)
  Got 1 result, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/gold/terra__validator_voting_power.yml/schema_test/dbt_expectations_expect_row_va_283bcc95116ffdf60baba7cd1789aac1.sql

Failure in test not_null_silver_terra__terraswap_pool_reserves_BLOCKCHAIN (models/terra/silver/silver_terra__terraswap_pool_reserves.yml)
  Got 8008935 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/silver/silver_terra__terraswap_pool_reserves.yml/schema_test/not_null_silver_terra__terraswap_pool_reserves_BLOCKCHAIN.sql

Failure in test dbt_utils_unique_combination_of_columns_terra__validator_voting_power_BLOCK_ID__ADDRESS (models/terra/gold/terra__validator_voting_power.yml)
  Got 172653924 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/gold/terra__validator_voting_power.yml/schema_test/dbt_utils_unique_combination_o_941a58f6fe3da792e7346382c2e33639.sql

Failure in test not_null_terra__validator_labels_DELEGATOR_ADDRESS (models/terra/gold/terra__validator_labels.yml)
  Got 6 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/gold/terra__validator_labels.yml/schema_test/not_null_terra__validator_labels_DELEGATOR_ADDRESS.sql

Failure in test not_null_terra__validator_labels_OPERATOR_ADDRESS (models/terra/gold/terra__validator_labels.yml)
  Got 6 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/gold/terra__validator_labels.yml/schema_test/not_null_terra__validator_labels_OPERATOR_ADDRESS.sql

Failure in test not_null_terra__validator_labels_VP_ADDRESS (models/terra/gold/terra__validator_labels.yml)
  Got 6 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/gold/terra__validator_labels.yml/schema_test/not_null_terra__validator_labels_VP_ADDRESS.sql

Database Error in test not_null_terraswap__pool_reserves_SYSTEM_CREATED_AT (models/terra/swap/terraswap__pool_reserves.yml)
  000904 (42000): SQL compilation error: error line 12 at position 6
  invalid identifier 'SYSTEM_CREATED_AT'
  compiled SQL at target/run/sql_models/models/terra/swap/terraswap__pool_reserves.yml/schema_test/not_null_terraswap__pool_reserves_SYSTEM_CREATED_AT.sql

Failure in test silver_terra__blocks__block_id-assert_no_gap (tests/terra/silver/silver_terra__blocks__block_id-assert_no_gap.sql)
  Got 44 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/tests/terra/silver/silver_terra__blocks__block_id-assert_no_gap.sql

Failure in test silver_terra__tax_rate__block_number-assert_no_gap (tests/terra/silver/silver_terra__tax_rate__block_number-assert_no_gap.sql)
  Got 39 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/tests/terra/silver/silver_terra__tax_rate__block_number-assert_no_gap.sql

Failure in test not_null_terra_sv__transactions_TX_CODE (models/terra/secure_views/terra_sv__transactions.yml)
  Got 97334724 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/secure_views/terra_sv__transactions.yml/schema_test/not_null_terra_sv__transactions_TX_CODE.sql

Failure in test not_null_terra_sv__transactions_CODESPACE (models/terra/secure_views/terra_sv__transactions.yml)
  Got 97334724 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/secure_views/terra_sv__transactions.yml/schema_test/not_null_terra_sv__transactions_CODESPACE.sql

Failure in test not_null_terra_sv__transactions_TX_STATUS_MSG (models/terra/secure_views/terra_sv__transactions.yml)
  Got 159910739 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/secure_views/terra_sv__transactions.yml/schema_test/not_null_terra_sv__transactions_TX_STATUS_MSG.sql

Failure in test terra__blocks__block_id-assert_no_gap (tests/terra/terra__blocks__block_id-assert_no_gap.sql)
  Got 44 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/tests/terra/terra__blocks__block_id-assert_no_gap.sql

Failure in test dbt_utils_unique_combination_of_columns_terra__gov_vote_BLOCK_ID (models/terra/gold/terra__gov_vote.yml)
  Got 3704 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/gold/terra__gov_vote.yml/schema_test/dbt_utils_unique_combination_o_ecb4dc52331303610ae122d73887cb2c.sql

Failure in test terra__tax_rate__block_number-assert_no_gap (tests/terra/terra__tax_rate__block_number-assert_no_gap.sql)
  Got 39 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/tests/terra/terra__tax_rate__block_number-assert_no_gap.sql

Failure in test dbt_utils_unique_combination_of_columns_mirror__gov_vote_TX_ID__BLOCK_ID (models/terra/mirror/mirror__gov_vote.yml)
  Got 2 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/mirror/mirror__gov_vote.yml/schema_test/dbt_utils_unique_combination_o_18f66bf8d3ea7aeea738dc28650bfd20.sql

Failure in test dbt_utils_unique_combination_of_columns_terra_sv__msgs_BLOCK_ID (models/terra/secure_views/terra_sv__msgs.yml)
  Got 5870197 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/secure_views/terra_sv__msgs.yml/schema_test/dbt_utils_unique_combination_of_columns_terra_sv__msgs_BLOCK_ID.sql

Failure in test dbt_utils_unique_combination_of_columns_terra_sv__transitions_BLOCK_ID (models/terra/secure_views/terra_sv__transitions.yml)
  Got 6333861 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/secure_views/terra_sv__transitions.yml/schema_test/dbt_utils_unique_combination_o_2d2506fd373bf3d6dbdd4994ad4a235b.sql

Failure in test terra__transitions__index-assert_no_gap (tests/terra/terra__transitions__index-assert_no_gap.sql)
  Got 2 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/tests/terra/terra__transitions__index-assert_no_gap.sql

Failure in test dbt_expectations_expect_row_values_to_have_recent_data_anchor__reward_claims_BLOCK_TIMESTAMP__day__1 (models/terra/anchor/anchor__reward_claims.yml)
  Got 1 result, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/anchor/anchor__reward_claims.yml/schema_test/dbt_expectations_expect_row_va_040f2034e0d4127596a068fd2e70c77e.sql

Failure in test dbt_utils_unique_combination_of_columns_anchor__liquidations_TX_ID__BLOCK_ID__BORROWER (models/terra/anchor/anchor__liquidations.yml)
  Got 893 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/anchor/anchor__liquidations.yml/schema_test/dbt_utils_unique_combination_o_62e65c5e7dd9de8365b74cc8aef15081.sql

Failure in test dbt_utils_unique_combination_of_columns_anchor__deposits_TX_ID__BLOCK_ID (models/terra/anchor/anchor__deposits.yml)
  Got 1 result, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/anchor/anchor__deposits.yml/schema_test/dbt_utils_unique_combination_o_f365d30fa6f8b3fa8e8ca8fac3f64138.sql

Failure in test dbt_utils_unique_combination_of_columns_anchor__repay_TX_ID__BLOCK_ID (models/terra/anchor/anchor__repay.yml)
  Got 629 results, configured to fail if != 0

  compiled SQL at target/compiled/sql_models/models/terra/anchor/anchor__repay.yml/schema_test/dbt_utils_unique_combination_o_6fe9558b9e829de15af98f99a63ca2c4.sql

Failure in test dbt_utils_unique_combination_of_columns_mirror__close_short_farm_TX_ID__BLOCK_ID (models/terra/mirror/mirror__close_short_farm.yml)
  Got 10 results, configured to fail if != 0

  compile [...]

2022-02-08 18:22 UTC, nickpayiatis approved these changes

2022-02-08 23:21 UTC, juls858 approved these changes

2022-02-09 18:41 UTC, merged

2022-02-13 22:52 UTC, juls858 approved these changes