add thorchain base tables
FlipsideCrypto/sql_models pull request #29
Opened 2021-07-12 19:32 UTC by XYGUAN

2021-07-16 21:54 UTC, James-Mission commented on models/thorchain/thorchain__bond_actions.sql
> +    materialized='incremental',
This could be a full reload it only had 3600 rows

2021-07-16 21:54 UTC, James-Mission commented on models/thorchain/thorchain__bond_actions.sql
> +    unique_key=["tx_id"],
Did we figure out that issue with the 000...000 tx_id?

2021-07-16 21:58 UTC, James-Mission commented on models/thorchain/thorchain__liquidity_actions.sql
> +    unique_key=["tx_id"],
there's dupes on this unique key:
select tx_id,
count(1)
from thorchain.liquidity_actions
group by 1
having count(1) > 1

2021-07-16 22:06 UTC, James-Mission commented on models/thorchain/thorchain__swaps.sql
> +    unique_key=["tx_id"],
there's dupes on that unique key:
select tx_id,
count(1)
from thorchain.swaps
group by 1
having count(1) > 1

2021-07-16 22:12 UTC, James-Mission commented on models/thorchain/thorchain__total_block_rewards.sql
> +    unique_key=["block_id"],
that isn't the unique key there's dupes:
select block_id,
count(1)
from thorchain.total_block_rewards
group by 1
having count(1) > 1

It looks to be block_id + reward_entity

2021-07-16 22:15 UTC, James-Mission commented on models/thorchain/thorchain__transfers.sql
> +    unique_key=["block_id", "asset", "from_address", "to_address"],
there's dupes on this unique key:
select block_id, 
asset, 
from_address, 
to_address,
count(1)
from thorchain.transfers
group by 1,2,3,4
having count(1) > 1

2021-07-16 22:23 UTC, James-Mission requested changes
See comments.

2021-07-19 00:57 UTC, XYGUAN commented on models/thorchain/thorchain__transfers.sql
> +    unique_key=["block_id", "asset", "from_address", "to_address"],
I traced back to the midgrad table and they have the tx_id there, the problem is our prior internal base table doesn't include the tx_id, I updated both tables "transfers_events" and "transfer"

2021-07-19 01:03 UTC, XYGUAN commented on models/thorchain/thorchain__total_block_rewards.sql
> +    unique_key=["block_id"],
Updated

2021-07-21 01:14 UTC, XYGUAN commented on models/thorchain/thorchain__transfers.sql
> +    unique_key=["block_id", "asset", "from_address", "to_address"],
Added the event_id as the unique id

2021-07-21 01:15 UTC, XYGUAN commented on models/thorchain/thorchain__swaps.sql
> +    unique_key=["tx_id"],
This duplication is not correct in the database, I can check this tx_id and there is just one tx_id

2021-07-21 01:20 UTC, XYGUAN commented on models/thorchain/thorchain__swaps.sql
> +    unique_key=["tx_id"],
I added the DISTINCT after SELECT

2021-07-21 16:11 UTC, James-Mission approved these changes

2021-07-21 20:59 UTC, merged