fair market value table in silver crosschain
FlipsideCrypto/sql_models pull request #536
Opened 2022-05-21 00:36 UTC by flipside-kellen

2022-05-21 00:37 UTC, flipside-kellen commented
<img width="1278" alt="Screen Shot 2022-05-20 at 5 36 46 PM" src="https://user-images.githubusercontent.com/83607882/169627330-7cf4e5d4-1b17-4cdd-96a8-f38100ac04f1.png">
Test results

2022-05-23 16:56 UTC, desmond-hui requested changes

2022-05-23 16:56 UTC, desmond-hui commented on models/crosschain/silver/silver_crosschain__nft_fair_market_value.sql
> +  cluster_by = ['collection', 'mint'],
Remove `unique_key` `incremental_strategy` `cluster_by` because this is a view, those configurations are ignored

2022-05-24 04:24 UTC, kblumberg commented on models/crosschain/silver/silver_crosschain__nft_fair_market_value.sql
> +  cluster_by = ['collection', 'mint'],
done

2022-05-24 15:07 UTC, merged